### ISSUE TITLE
feat: 기능 관련 todo

### ISSUE THREAD

**Issue by jenny-jione** [jenny-jione/hanja-project#4]
## gui window size custom
현재: gui_test.py, gui_search.py, gui_reading_test.py .. 모두 gui_base.py 안에 있는 setting 함수에 따라서 gui 설정이 정해지고 있음.
문제점: search의 경우 창의 길이가 test일 때와 분명히 달라야 함. 

- [x] gui_search.py를 실행할 때는 search에 맞춰진 창 size 설정으로 실행되도록 코드 수정하기

## accumulated_results.csv 재검사
현재: gui_test.py를 통해 틀린 문제들이 누적되어 accumulated_results.csv에 추가되고 있음
문제점: 한 번 추가된 항목들은 맞혀도 사라지지 않음

- [x] gui_test.py가 아닌 retest.py 등 새로운 모듈을 만들기
  - retest.py에서 맞은 항목은 mistake가 하나씩 줄어든다
  - 만약 원래 mistake가 1이었다면 아예 row에서 삭제

**Comment by jenny-jione** [comment]
## 획수 순서로 정렬한 파일 만들기
- [x] 가나다순으로는 뒤에 있지만 앞에 있는 한자에 포함되는 한자가 먼저 나오도록 하기.

- 예시
  - 조각 편(片)은 판목 판(版)보다 가나다순으로는 뒤에 있지만, 
  - 版 안에 片가 포함되어 있으므로(심지어 부수임) 片의 순서가 더 앞이어야 학습할 때 수월함.
- 정렬 기준
  1. 부수 (radical)
  2. 획수 (stroke count)
  3. 음(音) (representative pronunciation)
